# "version" is the configuration version, currently "1".
version: 1

merge:
  trigger:
    labels: ["merge when ready"]
    branches: ["main"]
    branch_patterns: ["feature/.*"]

  ignore:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash

  branch_method:
    develop: squash
    master: merge
  merge_method:
    - method: squash
      trigger:
        max_commits: 3
  options:
    squash:
      title: "pull_request_title"
      body: "empty_body"
  delete_after_merge: true
  allow_merge_with_no_checks: true

update:
  trigger:
    labels: ["WIP", "Update Me"]
  ignore:
    labels: ["Do Not Update"]
  ignore_drafts: false

  required_statuses:
    - "policy-bot: develop"
