# Excavator auto-updates this file. Please contribute improvements to the central template.

version: 1
merge:
  trigger:
    labels: ["merge when ready"]
  ignore:
    labels: ["do not merge"]
  method: squash
  options:
    allow_merge_with_no_checks: true
    squash:
      body: pull_request_body
      message_delimiter: ==COMMIT_MSG==
  delete_after_merge: true
update:
  trigger:
    labels: ["update me"]