policy:
  approval:
  - default 
  - updating test folder

approval_rules:
- name: default
- name: updating test folder
  if:
        only_changed_files:
          paths:
            - "test/.*"
  requires:
    count: 1
