# This policy will always approve every PR.

policy:
  approval:
    - or:
      - no approval necessary

approval_rules:
  - name: no approval necessary
    options:
      allow_contributor: false
    requires:
      count: 0