policy:
  approval:
  - no approval necessary

approval_rules:
- name: no approval necessary
  if:
      only_changed_files:
        paths:
        - '^staging\.palantir\.com/.*'
  requires:
    count: 1
