# the high level policy
policy:
  approval:
    - or:
        - one

# the list of rules
approval_rules:
  - name: one
    description: this is a dummy
    if:
      targets_branch:
        pattern: "^(master|main)$"
      from_branch:
        pattern: "^(feature/deploy)$"
