name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: deployment
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.head_ref }}
        shell: bash
      - run: wait 10000
        shell: bash
