name: Test

concurrency:
  group: deployment
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 10000
        shell: bash
